# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.23
# 
# >> macros
# << macros

Name:       repomd-pattern-builder
Summary:    Scripts to build patterns for the rpm repository.
Version:    0.2
Release:    1
Group:      Software Management/Package Manager
License:    GPLv2
URL:        https://gitorious.org/meego-developer-edition-for-n900/repomd-pattern-builder
Source0:    %{name}-%{version}.tar.xz
Source100:  repomd-pattern-builder.yaml
Requires:   python
Requires:   python-yaml
Requires:   python-lxml
Requires:   /usr/bin/xmllint


%description
Script that converts .yaml structures to suitable rpm patterns and package groups.




%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
install -D %{name}.py %{buildroot}/%{_bindir}/%{name}.py
# << install pre

# >> install post
# << install post






%files
%defattr(-,root,root,-)
# >> files
%{_bindir}/%{name}.py
# << files


